#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */

defined('YII_ENV') or define('YII_ENV', getenv('PROJECT_ENV'));
defined('YII_DEBUG') or define('YII_DEBUG', true);
error_reporting(-1);

require(__DIR__ . '/../composer/vendor/autoload.php');
require(__DIR__ . '/../composer/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/console/config/main.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
